### ISSUE TITLE
statistical jumpstart

### ISSUE THREAD

**Issue by jdkent** [HBClab/LabManual#4]
Daniel Lakens has two online courses on improving understanding of statistical results:
- https://www.coursera.org/learn/statistical-inferences/
- https://www.coursera.org/learn/improving-statistical-questions

Probably best for incoming graduate students and possibly for undergraduates doing an undergraduate research thesis

**Comment by jdkent** [comment]
[jeannette mumford is currently doing a series on mixed effects models](https://www.youtube.com/watch?v=IGHm1XHFWMc&list=PLB2iAtgpI4YEAUiEQ1ZnfMXY-yewNzn9z). this should be a great series.

**Comment by jdkent** [comment]
[An aggregated list of statistical concepts visualized](https://github.com/jdkent/visualizeStatisticsConcepts)

**Comment by mwvoss** [comment]
Added these links, thank you!
